### ISSUE TITLE
Warn when missing parenthesis when calling ecs_world.create_entity

### ISSUE THREAD

**Issue by owlen** [TheCheapestPixels/wecs#21] opened 2020-06-29 07:07 UTC
A common beginner bug is to call ecs_world.create_entity, and forgetting parenthesis for a component.
There is currently no warning and the system behaves weirdly. 

I suggets this:
https://github.com/owlen/wecs/commit/6c386d5215b4acef9e3208d0dd547c1ffc12c2f3
Please comment if acceptable and and whether something else shoud be raised, or another methodology for warnings exist.

**Comment by Schwarzbaer** [comment] 2020-06-29 08:11
Making sure you're getting the right types is always a good idea. The problem here is that there's no common base class for components, or it'd be a matter of `assert isinstance(c, Component)`. Adding one may be feasible, but I have no idea whether we'd lose flexibility in design.

**Comment by owlen** [comment] 2020-06-29 08:43
I see what you mean.
Do you agre that it's a good enough solution for now? I can create a PR for this.

**Comment by Schwarzbaer** [comment] 2020-06-29 11:29
Looks like this is a duplicate of https://github.com/TheCheapestPixels/wecs/issues/8

**Comment by owlen** [comment] 2020-07-01 04:17
It is indeed a duplicate.

**Closed as completed** 2020-07-01 04:16 UTC
